server:
  port: 0
  servlet:
    context-path: /bank-service
---
logging:
    file:
      path: ./
      name: banklogfile.log
---
springdoc:
  swagger-ui:
    path: /swagger

  api-docs:
    path: /api-docs
---
spring:
    datasource:
       url: jdbc:postgresql://localhost:5432/bank
       username: postgres
       password: Shkna1368


    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      database: POSTGRESQL
      hibernate:
       ddl-auto: update
---
spring:
  application:
    name: bank-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: true