server:
  port: 0
  servlet:
    context-path: /atm-service
---
springdoc:
  swagger-ui:
    path: /swagger

  api-docs:
    path: /api-docs

---


logging:
    file:
      path: ./
      name: atmlogfile.log
---



   spring:
     application:
       name: atm-service
   eureka:
     client:
       serviceUrl:
         defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
       enabled: true
